server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          username: seoLeir
          password: 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
          basedir: file://D:/VCSprojects/temp-cloud-config-server
          clone-on-start: true
          uri: https://github.com/seoLeir/spring-micro-demo-cloud-config-repo.git
          default-label: main
          force-pull: true
  application:
    name: github-cloud-config-server
