# Напрямое обращение к микросервису не принято
# Лучше указывать 0, при старте приложения этому микросервису будет присвоен рандомный порт
server:
  port: 0

# ID сервера eureka. Айди приложения
# Желательно указывать всегда в микросервисных приложениях
# По этому айди будет искаться instance приложения
spring:
  application:
    name: eclient2

eureka:
  client:
    # url куда будет происходить регистрация микросервисов
    service-url:
      defaultZone: http://localhost:8761/eureka